spring.application.name=educonnect
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/nik
spring.datasource.username=postgres
spring.datasource.password=Nikhil@86

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.servlet.SecurityAutoConfiguration