# App name
spring.application.name=EduConnect+

# Server port
server.port=8080

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/educonnect
spring.datasource.username=postgres
spring.datasource.password=Nikhil@86
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

# Disable security for now (we add it in Phase 5)
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# JWT Configuration
jwt.secret=educonnectplus-super-secret-key-nikhil-2026-very-long-string
jwt.expiration=900000
jwt.refresh-expiration=604800000